local data = {}

data.zones = {
	{name = "Ant Field", image = "rbxassetid://15617807338"},
	{name = "Bamboo Field", image = "rbxassetid://15617807109"},
	{name = "Blue Flower Field", image = "rbxassetid://15617806925"},
	{name = "Cactus Field", image = "rbxassetid://15617806727"},
	{name = "Clover Field", image = "rbxassetid://15617806641"},
	{name = "Coconut Field", image = "rbxassetid://15617838168"},
	{name = "Dandelion Field", image = "rbxassetid://15617826387"},
	{name = "Mountain Top Field", image = "rbxassetid://15617806273"},
	{name = "Mushroom Field", image = "rbxassetid://15617806189"},
	{name = "Pepper Patch", image = "rbxassetid://15617806096"},
	{name = "Pine Tree Forest", image = "rbxassetid://15617805993"},
	{name = "Pineapple Patch", image = "rbxassetid://15617805930"},
	{name = "Pumpkin Patch", image = "rbxassetid://15617805864"},
	{name = "Rose Field", image = "rbxassetid://15617805712"},
	{name = "Spider Field", image = "rbxassetid://15617806534"},
	{name = "Strawberry Field", image = "rbxassetid://15617805499"},
	{name = "Stump Field", image = "rbxassetid://15617805381"},
	{name = "Sunflower Field", image = "rbxassetid://15617805255"},
}

data.other = {
	{name = "Walk", image = "rbxassetid://15460472468"},
	{name = "Tween", image = "rbxassetid://15460472736"},
}

data.positions = {
	{name = "center", image = "rbxassetid://15617969456"},
	{name = "left",   image = "rbxassetid://15617968922"},
	{name = "right",  image = "rbxassetid://15617968590"},
}

data.mask = {
	{name = "Diamond Mask", image = "rbxassetid://2557828875"},
	{name = "Demon Mask", image = "rbxassetid://2557829605"},
	{name = "Gummy Mask", image = "rbxassetid://2557830185"},
	{name = "Bubble Mask", image = "rbxassetid://2558166299"},
	{name = "Fire Mask", image = "rbxassetid://2558167630"},
	{name = "Honey Mask", image = "rbxassetid://2558166990"},
	{name = "None", image = "rbxassetid://1554410815"},
}

data.pushrooms = {
	{name = "All Pushrooms"},
	{name = "Common"},
	{name = "Rare"},
	{name = "Epic"},
	{name = "Legendary"},
	{name = "Mythic"},
}

data.tokens = {
	-- eggs
	{name = "Silver Egg", image = "rbxassetid://1436888293"},
	{name = "Golden Egg", image = "rbxassetid://1436922459"},
	{name = "Diamond Egg", image = "rbxassetid://1436943264"},
	{name = "Basic Egg", image = "rbxassetid://1436887789"},
	{name = "Mythic Egg", image = "rbxassetid://4520708982"},
	{name = "Silver Star Egg", image = "rbxassetid://1987253833"},
	{name = "Golden Star Egg", image = "rbxassetid://1987255318"},
	{name = "Diamond Star Egg", image = "rbxassetid://1987257040"},
	{name = "Star Egg", image = "rbxassetid://2007771339"},

	-- tokens
	{name = "Black Bear", image = "rbxassetid://1472491940"},
	{name = "Brown Bear", image = "rbxassetid://1442859163"},
	{name = "Gummy Bear", image = "rbxassetid://1837410537"},
	{name = "Mother Bear", image = "rbxassetid://2032949183"},
	{name = "Panda Bear", image = "rbxassetid://1472580249"},
	{name = "Polar Bear", image = "rbxassetid://1472532912"},
	{name = "Science Bear", image = "rbxassetid://1489734171"},
	
	{name = "Red Boost", image = "rbxassetid://1442859163"},
	{name = "Blue Boost", image = "rbxassetid://1442863423"},
	{name = "White Boost", image = "rbxassetid://3877732821"},
	{name = "Buzz Bomb", image = "rbxassetid://1442725244"},
	{name = "Buzz Bomb Plus", image = "rbxassetid://1442764904"},
	{name = "Rage Ability", image = "rbxassetid://1442700745"},
	{name = "Focus", image = "rbxassetid://1629649299"},
	{name = "Photon", image = "rbxassetid://1671281844"},
	{name = "Star", image = "rbxassetid://2000457501"},
	{name = "Token Link", image = "rbxassetid://1629547638"},
	{name = "Baby Love", image = "rbxassetid://1472256444"},
	{name = "Red Sync", image = "rbxassetid://1874704640"},
	{name = "Blue Sync", image = "rbxassetid://1874692303"},
	{name = "Pollen Mark", image = "rbxassetid://2499540966"},
	{name = "Honey Mark", image = "rbxassetid://2499514197"},
	{name = "Cloud", image = "rbxassetid://3582501342"},
	{name = "Cloud Plus", image = "rbxassetid://3809516302"},
	{name = "Tornado", image = "rbxassetid://3582519526"},
	{name = "Fetch", image = "rbxassetid://2319100769"},
	{name = "Impale", image = "rbxassetid://2319083910"},
	{name = "Trail", image = "rbxassetid://2553784102"},
	{name = "Flame Heat", image = "rbxassetid://4097473201"},
	{name = "Inferno", image = "rbxassetid://4519549299"},
	{name = "Flame Fuel", image = "rbxassetid://4528208186"},
	{name = "Mark Surge", image = "rbxassetid://4528379338"},
	{name = "Summon Frog", image = "rbxassetid://4528414666"},
	{name = "Flower Flip", image = "rbxassetid://4889486022"},
	{name = "Bubble Bloat", image = "rbxassetid://5144723635"},
	{name = "Fuzz Bombs", image = "rbxassetid://4889308332"},
	{name = "Inflate Balloon", image = "rbxassetid://8083436978"},
	{name = "Balloon Blessing", image = "rbxassetid://8083443467"},
	{name = "SCPR", image = "rbxassetid://8172536505"},
	{name = "Balloon", image = "rbxassetid://8045544966"},
	{name = "Coconut Combo", image = "rbxassetid://17362698291"},
	{name = "Large White Flower", image = "rbxassetid://1442836863"},
	{name = "Sigather", image = "rbxassetid://1999448629"},
}

data.token_resources = {
	-- drops
	{name = "Honey Drop", image = "rbxassetid://1472108387"},
	{name = "Royal Jelly", image = "rbxassetid://1471882621"},
	{name = "Ticket", image = "rbxassetid://1674871631"},
	{name = "Gumdrops", image = "rbxassetid://1838129169"},
	{name = "Pineapple", image = "rbxassetid://1952796032"},
	{name = "Strawberry", image = "rbxassetid://1952740625"},
	{name = "Sunflower Seed", image = "rbxassetid://1952682401"},
	{name = "Star Treat", image = "rbxassetid://2028603146"},
	{name = "Treat", image = "rbxassetid://2028574353"},
	{name = "Moon Charm", image = "rbxassetid://2306224708"},
	{name = "Ant Pass", image = "rbxassetid://2060626811"},
	{name = "Star Jelly", image = "rbxassetid://2319943273"},
	{name = "Oil", image = "rbxassetid://2545746569"},
	{name = "Blue Extract", image = "rbxassetid://2495936060"},
	{name = "Glue", image = "rbxassetid://2504978518"},
	{name = "Spike", image = "rbxassetid://2314214749"},
	{name = "Magic Bean", image = "rbxassetid://2529092020"},
	{name = "Glitter", image = "rbxassetid://2542899798"},
	{name = "Enzyme", image = "rbxassetid://2584584968"},
	{name = "Micro Converter", image = "rbxassetid://2863122826"},
	{name = "Festive Bean", image = "rbxassetid://2676715441"},
	{name = "Night Bell", image = "rbxassetid://2676671613"},
	{name = "MB1", image = "rbxassetid://3027672238"},
	{name = "Coconut", image = "rbxassetid://3012679515"},
	{name = "Cloud Vial", image = "rbxassetid://3030569073"},
	{name = "Tropical Drink", image = "rbxassetid://3835877932"},
	{name = "Neon Berry", image = "rbxassetid://4483267595"},
	{name = "Bitter Berry", image = "rbxassetid://4483230719"},
	{name = "Atomic Treat", image = "rbxassetid://4520736128"},
	{name = "Super Smoothie", image = "rbxassetid://5144657109"},
	{name = "Purple Potion", image = "rbxassetid://4935580111"},
	{name = "Gingerbread", image = "rbxassetid://6077173317"},
	{name = "Snowflake", image = "rbxassetid://6087969886"},
	{name = "Honey Suckle", image = "rbxassetid://8277901755"},
	{name = "Turpentine", image = "rbxassetid://8310376128"},
	{name = "Caustic Wax", image = "rbxassetid://8277781666"},
	{name = "Whirligig", image = "rbxassetid://8277898895"},
	{name = "Soft Wax", image = "rbxassetid://8277778300"},
	{name = "Hard Wax", image = "rbxassetid://8277780065"},
	{name = "Festive Planter", image = "rbxassetid://8310370747"},
}

data.all_tokens = {}
for _, v in ipairs(data.token_resources) do
	table.insert(data.all_tokens, v)
end
for _, v in ipairs(data.tokens) do
	table.insert(data.all_tokens, v)
end

data.actives = {
	--auto_farm
	auto_farm = false, -- test
	auto_sprinkler = false,
	auto_dig = false,
	point = false,
	lines = false,
	auto_farm_speed = 80,
	style_auto_farm = "Walk",
	position_field = "center",
	selected_field = "Blue Flower Field",
	
	--convert
	balloon = false,
	honey_mask = false,
	backpack = 80,
	auto_convert = 20,
	mask = "None",
	converting = false,
	last_time_convert = 0,
	
	--farm settings
	collect_bubbles = false,
	bubble_priority = 49,
	petals = false,
	wealth_clock = true,
	mondo = false,
	sprout_cooldown = 30,
	hive_choice = "Random",
	petal_colors = {__init = true, Red = true, Blue = true, White = true, Green = true, Black = true, Yellow = true, Scarlet = true, Cyan = true,
		Grey = true, Violet = true, Pink = true, Merigold = true, Periwinkle = true,},
	
	--pushrooms = false,
	pushrooms_enabled = false,
	pushrooms = "All Pushrooms",
	sprouts = false,
	mondo_collect_time = 40,
	mondo_collect_drop = true,
	save_mode = true,
	
	--server
	auto_rejoin = true,
	server_free = true,
	server_private = false,
	server_mode = nil,
	private_server_link = "",

	--options
	hide_decorations = false,
	hide_field_decorations = true,

	--move_to
	move = false,
	move_speed = 100,

	--other
	script_name = "Nectar 0.0.5",
	position_script = UDim2.new(0.22, 0, 0.5, 0),
	walkspeed = 40,
	autohive = true,
	anti_afk = true,
	
	--tokens
	token_priorities = {
		--eggs
		["Mythic Egg"] = 249,
		["Star Egg"] = 249,
		["Diamond Star Egg"] = 249,
		["Golden Star Egg"] = 249,
		["Silver Star Egg"] = 249,
		["Diamond Egg"] = 249,
		["Golden Egg"] = 249,
		["Silver Egg"] = 249,
		
		--top drops
		["Star Treat"] = 199,
		["Star Jelly"] = 199,
		["Magic Bean"] = 199,
		["Festive Bean"] = 199,
		["Atomic Treat"] = 199,
		["Super Smoothie"] = 249,
		["Purple Potion"] = 249,
		["Turpentine"] = 249,
		["Caustic Wax"] = 199,
		["Hard Wax"] = 199,
		["Soft Wax"] = 199,
		["Glitter"] = 249,
		["Enzyme"] = 199,
		["Oil"] = 199,
		["Blue Extract"] = 199,
		["Glue"] = 249,
		["Moon Charm"] = 199,
		["Festive Planter"] = 249,
		["Night Bell"] = 249,
		["Tropical Drink"] = 249,
		["Neon Berry"] = 199,
		["Bitter Berry"] = 199,
		["Gingerbread"] = 249,
		["Snowflake"] = 249,
		["Ticket"] = 249,
		["Gumdrops"] = 249,
		["Pineapple"] = 199,
		["Strawberry"] = 199,
		["Sunflower Seed"] = 199,

		--normal drops
		["Honey Drop"] = 29,
		["Royal Jelly"] = 29,
		["Treat"] = 29,
		["Ant Pass"] = 29,
		["Spike"] = 29,
		["Micro Converter"] = 29,
		["MB1"] = 29,
		["Coconut"] = 29,
		["Cloud Vial"] = 29,
		["Honey Suckle"] = 29,
		["Whirligig"] = 29,
		["Basic Egg"] = 29,
		
		--top tokens
		["Black Bear"] = 149,
		["Brown Bear"] = 149,
		["Gummy Bear"] = 149,
		["Mother Bear"] = 149,
		["Panda Bear"] = 149,
		["Polar Bear"] = 149,
		["Science Bear"] = 149,
		["Balloon Blessing"] = 149,
		["Balloon"] = 149,
		["Focus"] = 149,
		["White Boost"] = 149,
		["Large White Flower"] = 149,
		["Token Link"] = 149,
		["Blue Boost"] = 149,
		["Buzz Bomb Plus"] = 99,
		["Buzz Bomb"] = 99,
		["Baby Love"] = 149,
		["Honey Mark"] = 99,
		["Pollen Mark"] = 99,
		["Star"] = 99,
		["Blue Sync"] = 99,
		["Fetch"] = 99,
		["Fuzz Bombs"] = 99,
		["Bubble Bloat"] = 149,
		["Flower Flip"] = 149,
		["Summon Frog"] = 149,
		["Mark Surge"] = 99,
		["Photon"] = 99,

		--normal tokens
		["Sigather"] = 49,
		["Coconut Combo"] = 49,
		["SCPR"] = 49,
		["Inflate Balloon"] = 49,
		["Flame Fuel"] = 49,
		["Inferno"] = 49,
		["Flame Heat"] = 49,
		["Trail"] = 49,
		["Impale"] = 49,
		["Tornado"] = 49,
		["Cloud Plus"] = 49,
		["Cloud"] = 49,
		["Red Sync"] = 49,
		["Rage Ability"] = 49,
		["Red Boost"] = 49,
	},
}

return data
